//go:build darwin || linux
// +build darwin linux

package exercises

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"syscall"

	"github.com/abxda/bdpv6-launcher/internal/paths"
)

// OpenBashSession (Unix) spawns a new Terminal window on macOS via
// `open -a Terminal <script>`. The script is a one-shot wrapper that
// exports JAVA_HOME / HADOOP_HOME / PATH, cd's into the exercise dir,
// prints a teacher's cheat sheet, and then `exec bash` so the student
// gets an interactive shell with everything ready.
//
// On Linux the "spawn a new terminal window" pattern is desktop-env
// specific (gnome-terminal, konsole, xterm, ...) so we just return a
// helpful error pointing at the script file the user can source from
// any terminal they already have open.
func OpenBashSession(p *paths.Paths, ex Exercise) error {
	scriptPath, err := writeWelcomeBashUnix(p, ex)
	if err != nil {
		return fmt.Errorf("escribir script de bienvenida: %w", err)
	}

	if runtime.GOOS != "darwin" {
		return fmt.Errorf("Abrir Bash automático no soportado en Linux. Abre tu terminal y ejecuta:\n  source %s", scriptPath)
	}

	cmd := exec.Command("open", "-a", "Terminal", scriptPath)
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("open -a Terminal: %w", err)
	}
	return nil
}

// bashLaunchSysAttr is a stub on Unix — we never spawn a hidden parent
// process on Mac/Linux. Lives here so the cross-platform build succeeds.
func bashLaunchSysAttr() *syscall.SysProcAttr { return nil }

// writeWelcomeBashUnix writes an executable .command script (macOS
// recognises .command files as "open in Terminal" by default) with the
// exact env, cd, and banner the student needs.
func writeWelcomeBashUnix(p *paths.Paths, ex Exercise) (string, error) {
	dir := p.Logs
	if dir == "" {
		dir = os.TempDir()
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	// .command extension so a double-click in Finder would also work.
	path := filepath.Join(dir, "bash-launcher-"+ex.ID+".command")

	pythonBin := filepath.Join(p.Python, "bin")

	body := `#!/bin/bash
# Auto-generated by BDPV6 Launcher for exercise ` + ex.ID + `.

export JAVA_HOME="` + p.CommonJDK + `"
export HADOOP_HOME="` + p.Hadoop + `"
export HADOOP_CONF_DIR="` + p.HadoopConf + `"
export PATH="$JAVA_HOME/bin:$HADOOP_HOME/bin:` + pythonBin + `:$PATH"

cd "` + ex.Path + `" 2>/dev/null || true

clear
cat <<BANNER
================================================================
  Consola BDP — ` + ex.Title + `
================================================================

 Entorno listo:
   JAVA_HOME    = $JAVA_HOME
   HADOOP_HOME  = $HADOOP_HOME
   cwd          = $(pwd)

 Comandos útiles (esta carpeta):
   ls                                  # archivos del ejercicio
   head *.csv                          # primeras líneas del input

 HDFS:
   hdfs dfs -ls /` + ex.ID + `/input          # ver input subido
   hdfs dfs -ls /` + ex.ID + `/output         # ver output del job
   hdfs dfs -cat /` + ex.ID + `/output/part-00000 | head -20
   hdfs dfsadmin -safemode get        # ¿está HDFS listo?

 Probar mapper+reducer SIN Hadoop (pipe Unix):
   cat *.csv | python3 mapper.py | sort | python3 reducer.py | head

 Lanzar el job MapReduce a mano:
   hadoop jar \$HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-*.jar \\
       -Dmapreduce.framework.name=local \\
       -mapper 'python3 mapper.py' -reducer 'python3 reducer.py' \\
       -input /` + ex.ID + `/input -output /` + ex.ID + `/output

 Tip: escribe 'exit' o pulsa Ctrl+D para cerrar esta consola.
================================================================
BANNER

exec bash
`
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return "", err
	}
	return path, nil
}
