package exercises

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/abxda/bdpv6-launcher/internal/paths"
)

// OpenBashSession spawns a new git-bash.exe window pre-configured with the
// JDK / Hadoop / Python env vars, cd'd to the exercise directory, and
// greeted with a teacher-written cheat-sheet of useful commands.
//
// The shell is fully interactive — the student can type whatever they want
// (hdfs dfs -ls, python mapper.py | sort | python reducer.py, etc.) without
// having to remember the env setup themselves.
//
// Implementation: writes a one-shot bashrc to <data>/.bash-launcher-<id>.rc
// then spawns git-bash via cmd /c start so the window is detached from the
// launcher process. The bashrc sets env, cd's, prints the welcome, then
// sources the user's normal ~/.bashrc so their aliases still work.
func OpenBashSession(p *paths.Paths, ex Exercise) error {
	bashExe := resolveGitBash(p)
	if bashExe == "" {
		return fmt.Errorf("no encontré git-bash.exe en la distribución (esperaba bash/git-bash.exe)")
	}

	rcPath, err := writeWelcomeBashrc(p, ex)
	if err != nil {
		return fmt.Errorf("escribir bashrc temporal: %w", err)
	}

	// Spawn detached via cmd /c start "" ... so the bash window has its own
	// lifecycle and the launcher process keeps going. The empty "" is the
	// window title arg that `start` needs when the next token is quoted.
	args := []string{
		"/c", "start", "", bashExe,
		"--no-needs-console",
		"--cd=" + toForwardSlash(ex.Path),
		"-i", "-l",
		"/usr/bin/bash", "--rcfile", toForwardSlash(rcPath),
	}
	cmd := exec.Command("cmd.exe", args...)
	cmd.SysProcAttr = bashLaunchSysAttr()
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("lanzar bash: %w", err)
	}
	// We deliberately don't Wait() — the bash window outlives this call.
	return nil
}

// resolveGitBash prefers the bundled git-bash.exe (so the student doesn't
// need Git for Windows installed) and falls back to PATH.
func resolveGitBash(p *paths.Paths) string {
	candidates := []string{
		filepath.Join(p.ScriptDir, "bash", "git-bash.exe"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	if found, err := exec.LookPath("git-bash"); err == nil {
		return found
	}
	return ""
}

// writeWelcomeBashrc materialises a one-shot bashrc that sets env vars,
// cd's into the exercise dir, prints a friendly Spanish cheat sheet, then
// chains into the user's normal ~/.bashrc so their PS1 / aliases / prompts
// still work. Returns the absolute path of the file.
func writeWelcomeBashrc(p *paths.Paths, ex Exercise) (string, error) {
	dir := p.Logs
	if dir == "" {
		dir = os.TempDir()
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "bash-launcher-"+ex.ID+".rc")

	javaHome := toForwardSlash(p.CommonJDK)
	hadoopHome := toForwardSlash(p.Hadoop)
	hadoopConf := toForwardSlash(p.HadoopConf)
	python := toForwardSlash(p.Python)
	exDir := toForwardSlash(ex.Path)
	id := ex.ID

	body := `# Auto-generated by BDPV6 Launcher for exercise ` + ex.ID + `.
# Sets env so 'hdfs', 'hadoop', 'python' all resolve from this distro.

export JAVA_HOME="` + javaHome + `"
export HADOOP_HOME="` + hadoopHome + `"
export HADOOP_CONF_DIR="` + hadoopConf + `"
export PATH="$JAVA_HOME/bin:$HADOOP_HOME/bin:` + python + `:` + python + `/Scripts:$PATH"

cd "` + exDir + `" 2>/dev/null

# Source the user's normal bashrc so their prompt and aliases keep working.
[ -f ~/.bashrc ] && source ~/.bashrc

# --- Welcome / cheat sheet ----------------------------------------------
echo ""
echo "================================================================"
echo "  Consola BDP — ` + ex.Title + `"
echo "================================================================"
echo ""
echo " Entorno listo:"
echo "   JAVA_HOME    = $JAVA_HOME"
echo "   HADOOP_HOME  = $HADOOP_HOME"
echo "   cwd          = $(pwd)"
echo ""
echo " Comandos útiles (esta carpeta):"
echo "   ls                                  # archivos del ejercicio"
echo "   cat breweries.csv | head            # ver primeras líneas del input"
echo ""
echo " HDFS:"
echo "   hdfs dfs -ls /` + id + `/input             # ver input subido"
echo "   hdfs dfs -ls /` + id + `/output            # ver output del job"
echo "   hdfs dfs -cat /` + id + `/output/part-00000 | head -20"
echo "   hdfs dfsadmin -safemode get         # ¿está HDFS listo?"
echo ""
echo " Probar mapper+reducer SIN Hadoop (en pipe Unix):"
echo "   cat breweries.csv | python mapper.py | sort | python reducer.py | head"
echo ""
echo " Lanzar el job MapReduce a mano:"
echo "   hadoop jar \$HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-*.jar \\"
echo "       -Dmapreduce.framework.name=local \\"
echo "       -mapper 'python mapper.py' -reducer 'python reducer.py' \\"
echo "       -input /` + id + `/input -output /` + id + `/output"
echo ""
echo " Tip: escribe 'exit' para cerrar esta consola."
echo "================================================================"
echo ""
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// toForwardSlash gives a path-style Git-Bash understands (it accepts
// either /d/foo or D:/foo for Windows drives; we use the slash form
// since it works inside bash strings without any escaping).
func toForwardSlash(p string) string { return strings.ReplaceAll(p, `\`, `/`) }
