//go:build windows
// +build windows

package exercises

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"

	"github.com/abxda/bdpv6-launcher/internal/paths"
)

// OpenBashSession (Windows) spawns a new interactive mintty + bash
// window pre-configured with the JDK / Hadoop / Python env vars,
// cd'd to the exercise directory, and greeted with a Spanish teacher's
// cheat sheet of useful commands.
//
// We bypass git-bash.exe and call mintty.exe + bash.exe directly because
// git-bash's argument forwarding is fragile: passing both --cd= options
// and an inner bash command line at once results in "/usr/bin/bash:
// cannot execute binary file" (git-bash mis-parses the args and tries to
// run /usr/bin/bash as a script). Driving mintty directly is what
// git-bash itself does internally — same UX, no foot-gun.
func OpenBashSession(p *paths.Paths, ex Exercise) error {
	bashRoot := filepath.Join(p.ScriptDir, "bash")
	mintty := filepath.Join(bashRoot, "usr", "bin", "mintty.exe")
	bash := filepath.Join(bashRoot, "usr", "bin", "bash.exe")
	if _, err := os.Stat(mintty); err != nil {
		return fmt.Errorf("no encontré mintty.exe en bash/usr/bin/ — ¿está el bash portable copiado en la distribución?")
	}
	if _, err := os.Stat(bash); err != nil {
		return fmt.Errorf("no encontré bash.exe en bash/usr/bin/")
	}

	rcPath, err := writeWelcomeBashrcWindows(p, ex)
	if err != nil {
		return fmt.Errorf("escribir bashrc temporal: %w", err)
	}

	icon := filepath.Join(bashRoot, "mingw64", "share", "git", "git-for-windows.ico")
	args := []string{"/c", "start", "", mintty, "-h", "always"}
	if _, err := os.Stat(icon); err == nil {
		args = append(args, "-i", icon)
	}
	args = append(args,
		"-e", bash,
		"--rcfile", toForwardSlash(rcPath),
		"-i",
	)

	cmd := exec.Command("cmd.exe", args...)
	cmd.Dir = ex.Path
	cmd.Env = bashLaunchEnv(p)
	cmd.SysProcAttr = bashLaunchSysAttr()
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("lanzar mintty+bash: %w", err)
	}
	return nil
}

// bashLaunchSysAttr hides the cmd.exe stub window that briefly appears
// when we spawn `cmd /c start ... mintty.exe`. The mintty window
// itself is independent and visible — only the launcher stub is hidden.
func bashLaunchSysAttr() *syscall.SysProcAttr {
	return &syscall.SysProcAttr{HideWindow: true}
}

// bashLaunchEnv composes the environment the spawned bash will inherit.
func bashLaunchEnv(p *paths.Paths) []string {
	overrides := map[string]string{
		"JAVA_HOME":           p.CommonJDK,
		"HADOOP_HOME":         p.Hadoop,
		"HADOOP_CONF_DIR":     p.HadoopConf,
		"MSYS_NO_PATHCONV":    "1",
		"MSYS2_ARG_CONV_EXCL": "*",
	}
	pathDirs := []string{
		filepath.Join(p.CommonJDK, "bin"),
		filepath.Join(p.Hadoop, "bin"),
		p.Python,
		filepath.Join(p.Python, "Scripts"),
	}
	overrides["PATH"] = mergePath(pathDirs)
	return mergeOSEnv(overrides)
}

// writeWelcomeBashrcWindows materialises a one-shot bashrc for the
// Windows mintty session. Sources /etc/profile first so /usr/bin
// (ls, cat, grep, sort, head) lands on PATH, then layers BDP overrides.
func writeWelcomeBashrcWindows(p *paths.Paths, ex Exercise) (string, error) {
	dir := p.Logs
	if dir == "" {
		dir = os.TempDir()
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "bash-launcher-"+ex.ID+".rc")

	javaHome := toForwardSlash(p.CommonJDK)
	hadoopHome := toForwardSlash(p.Hadoop)
	hadoopConf := toForwardSlash(p.HadoopConf)
	python := toForwardSlash(p.Python)
	exDir := toForwardSlash(ex.Path)
	id := ex.ID

	body := `# Auto-generated by BDPV6 Launcher for exercise ` + ex.ID + `.

# ---- FIRST: load the MSYS base environment ------------------------------
# bash invoked with --rcfile (and without --login) does NOT source
# /etc/profile, so /usr/bin (where ls, cat, grep, sort, head, find, etc.
# live) ends up missing from PATH. Without this line every basic Unix
# command fails with "command not found".
[ -f /etc/profile ] && . /etc/profile

# ---- THEN: layer our BDP overrides on top ------------------------------
export JAVA_HOME="` + javaHome + `"
export HADOOP_HOME="` + hadoopHome + `"
export HADOOP_CONF_DIR="` + hadoopConf + `"
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'
export PATH="$JAVA_HOME/bin:$HADOOP_HOME/bin:` + python + `:` + python + `/Scripts:$PATH"

[ -f ~/.bashrc ] && source ~/.bashrc

cd "` + exDir + `" 2>/dev/null

echo ""
echo "================================================================"
echo "  Consola BDP — ` + ex.Title + `"
echo "================================================================"
echo ""
echo " Entorno listo:"
echo "   JAVA_HOME    = $JAVA_HOME"
echo "   HADOOP_HOME  = $HADOOP_HOME"
echo "   cwd          = $(pwd)"
echo ""
echo " Tip: usa 'hdfs.cmd' y 'hadoop.cmd' (no 'hdfs' / 'hadoop' a secas)"
echo "      porque bash en MSYS prefiere los scripts Linux que vienen sin"
echo "      extension y no funcionan correctamente en Windows."
echo ""
echo " Comandos útiles (esta carpeta):"
echo "   ls                                  # archivos del ejercicio"
echo "   cat breweries.csv | head            # ver primeras líneas del input"
echo ""
echo " HDFS:"
echo "   hdfs.cmd dfs -ls /` + id + `/input         # ver input subido"
echo "   hdfs.cmd dfs -ls /` + id + `/output        # ver output del job"
echo "   hdfs.cmd dfs -cat /` + id + `/output/part-00000 | head -20"
echo "   hdfs.cmd dfsadmin -safemode get     # ¿está HDFS listo?"
echo ""
echo " Probar mapper+reducer SIN Hadoop (en pipe Unix):"
echo "   cat breweries.csv | python mapper.py | sort | python reducer.py | head"
echo ""
echo " Lanzar el job MapReduce a mano:"
echo "   hadoop.cmd jar \$HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-*.jar \\"
echo "       -Dmapreduce.framework.name=local \\"
echo "       -mapper 'python mapper.py' -reducer 'python reducer.py' \\"
echo "       -input /` + id + `/input -output /` + id + `/output"
echo ""
echo " Tip: escribe 'exit' o pulsa Ctrl+D para cerrar esta consola."
echo "================================================================"
echo ""
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
