package setup

import (
	"bytes"
	"os"
	"strings"
	"text/template"

	"github.com/abxda/bdpv6-launcher/internal/paths"
)

// WriteHadoopXML regenerates core-site.xml and hdfs-site.xml under the
// Hadoop conf dir, replacing any contaminated values (e.g. the
// /Users/Sl4sh3r99/... paths shipped in BDPV5_macOS) with file:/// URIs
// rooted at the current SCRIPT_DIR. Safe to call multiple times.
func WriteHadoopXML(p *paths.Paths) error {
	data := struct {
		URI string
	}{
		URI: uriPath(p.ScriptDir),
	}
	if err := writeTemplate(p.CoreSiteXML(), coreSiteTmpl, data); err != nil {
		return err
	}
	return writeTemplate(p.HdfsSiteXML(), hdfsSiteTmpl, data)
}

// uriPath turns an absolute filesystem path into a file:// URI the way
// Hadoop expects it: forward slashes only, three slashes after the scheme.
// On Windows, "D:\BDP\X" → "file:///D:/BDP/X". On macOS / Linux,
// "/Users/abel/BDP" → "file:///Users/abel/BDP".
func uriPath(absPath string) string {
	p := strings.ReplaceAll(absPath, `\`, `/`)
	if strings.HasPrefix(p, "/") {
		return "file://" + p
	}
	return "file:///" + p
}

func writeTemplate(dest, tmplText string, data interface{}) error {
	t, err := template.New("").Parse(tmplText)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	return os.WriteFile(dest, buf.Bytes(), 0o644)
}

const coreSiteTmpl = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by BDPV6 Launcher (do not edit by hand; values are derived from SCRIPT_DIR). -->
<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:9000</value>
    </property>
    <property>
        <name>hadoop.tmp.dir</name>
        <value>{{.URI}}/data/hadoop_tmp</value>
    </property>
</configuration>
`

const hdfsSiteTmpl = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by BDPV6 Launcher (do not edit by hand; values are derived from SCRIPT_DIR). -->
<configuration>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
    </property>
    <property>
        <name>dfs.namenode.name.dir</name>
        <value>{{.URI}}/data/hdfs/namenode</value>
    </property>
    <property>
        <name>dfs.datanode.data.dir</name>
        <value>{{.URI}}/data/hdfs/datanode</value>
    </property>
    <property>
        <name>dfs.permissions.enabled</name>
        <value>false</value>
    </property>
</configuration>
`
